### PR TITLE
inheirit macros instead of replicate macros

### PR DESCRIPTION
**Pull request by dataders**
adding `dependencies=['bigquery']` to `AdapterPlugin` should obviate the need to replicate the bigquery adapter macros.

I am curious about the inheiritance structure. Why does `LayerBigQueryAdapter` inheirit from both `LayerAdapter` and `BigQuery` adapter, when both `LayerAdapter` and `BigQuery` inherit from `BaseAdapter`?

https://github.com/layerai/dbt-adapters/blob/ff81d307ccb1b204b37167c9edf3fd45033a4971/dbt/adapters/layer_bigquery/impl.py#L7

### CODE REVIEW

**Comment by maasg** [comment]
Hi @dataders,  thanks a ton for this PR and for shining the way on this much easier dependency mechanism for macros.
I gave it a shot to make it work but I faced some hurdles. I guess that we still need the `profile_template.yaml` in place, which gets removed in this patch. Where should that go otherwise?

Regarding the inheritance, our plan is to expand support to other adapters.  `LayerAdapter` is there to add Layer specific code that’s common to all future adapters. Probably it doesn't need to inherit from `BaseAdapter`. 

It's early days for us in `dbt` land. Thanks again for showing us a better way!

**Comment by volkangurel** [comment]
Thank you so much for your contribution @dataders! I looked into this a bit and made our Titanic example work with these two commits:
https://github.com/layerai/dbt-adapters/commit/3c98a2d94b08578ff6bb8c434480d8ee5f56092c - this fixed a formatting issue in `pyproject.toml`
https://github.com/layerai/dbt-adapters/commit/58bab1a8a56477ccd706b9ba255687b85b5f150d - this added back two basic, required files in the `include/layer_bigquery` directory and fixed another issue that surfaced after the inheritance started working

Would you mind cherry picking them onto your PR if they look good to you?

**Comment by volkangurel** [comment]
@dataders I've created another PR with the changes mentioned above, while preserving your commit in that PR. Thank you very much for showing us this better way, much appreciated!

**Comment by dataders** [comment]
closing in favor of #67

**Pull request closed without merging**
